# fly.toml app configuration file generated for csvgateway on 2023-11-26T07:09:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "csvgateway"
primary_region = "arn"
console_command = "/code/manage.py shell"


[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="csvgateway_uploads"
  destination="/uploads"
  initial_size = "1"
  auto_extend_size_threshold = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static"
